[
  {
    "id": 1,
    "domain": "www.tribalwars.com.br",
    "hostOnly": true,
    "httpOnly": true,
    "name": "PHPSESSID",
    "path": "/",
    "sameSite": "unspecified",
    "secure": true,
    "session": true,
    "storeId": "0",
    "value": "rr8m9gdk1b7luihij523lqlpnqg291qd76sc1958733guag0"
  },
  {
    "id": 2,
    "domain": "www.tribalwars.com.br",
    "hostOnly": true,
    "httpOnly": false,
    "name": "ref",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": true,
    "storeId": "0",
    "value": "start"
  },
  {
    "id": 3,
    "domain": "www.tribalwars.com.br",
    "expirationDate": 1798723084.0,
    "hostOnly": true,
    "httpOnly": false,
    "name": "remember_optout",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "0"
  },
  {
    "id": 4,
    "domain": ".tribalwars.com.br",
    "expirationDate": 1769779084.0,
    "hostOnly": false,
    "httpOnly": true,
    "name": "br_auth",
    "path": "/",
    "sameSite": "unspecified",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "c0e1187f62c0:92f897c1a0db07d0e1ce96e8ddd50a7c4fed6bf6f52f7d7016e74e12daef2b8b"
  },
  {
    "id": 5,
    "domain": ".tribalwars.com.br",
    "expirationDate": 1798723020.0,
    "hostOnly": false,
    "httpOnly": false,
    "name": "cid",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "1273120814"
  },
  {
    "id": 6,
    "domain": "br138.tribalwars.com.br",
    "hostOnly": true,
    "httpOnly": false,
    "name": "websocket_available",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": true,
    "storeId": "0",
    "value": "true"
  },
  {
    "id": 7,
    "domain": "br138.tribalwars.com.br",
    "hostOnly": true,
    "httpOnly": false,
    "name": "global_village_id",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": true,
    "storeId": "0",
    "value": "9542"
  },
  {
    "id": 8,
    "domain": "br138.tribalwars.com.br",
    "hostOnly": true,
    "httpOnly": true,
    "name": "sid",
    "path": "/",
    "sameSite": "unspecified",
    "secure": true,
    "session": true,
    "storeId": "0",
    "value": "0%3Aa8fb6765eed17322c755c16c0830a9ad89306a2b82070cb965482601d4fe4124375c3e99e081bebd59e88f87a2511736e8a797b7d8fb117da87b7d30bdc6d6aa"
  }
]
